using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SMP
{
	class DataValues
	{
		enum Blocks {
			Air = 0,
			Stone = 1,
			Dirt = 3,
			CobbleStone = 4,
			WoodenPlank = 5,
			Sapling = 6,
			Bedrock = 7,
			AWater = 8,
			SWater = 9,
			ALava = 10,
			SLava = 11,
			Sand = 12,
			Gravel = 13,
			GoldOre = 14,
			IronOre = 15,
			CoalOre = 16,
			Wood = 17,
			Leaves = 18,
			//Sponge = 19,
			Glass = 20,
			LapisOre = 21,
			LapisBlock = 22,
			Dispenser = 23,
			SandStone = 24,
			NoteBlock = 25,
			Bed = 26,
			RailPowered = 27,
			RailDetector = 28,
			PistonSticky = 29,
			CobWeb = 30,
			TallGrass = 31,
			DeadShrubs = 32,
			Piston = 33,
			PistonExtension = 34,
			Wool = 35,
			BlockMovedByPiston = 36,
			FlowerDandelion = 37,
			FlowerRose = 38,
			MushroomBrown = 39,
			MushroomRed = 40,
			GoldBlock = 41,
			IronBlock = 42,
			SlabsDouble = 43,
			Slabs = 44,
			Brick = 45,
			TNT = 46,
			Bookshelf = 47,
			MossStone = 48,
			Obsidian = 49,
			Torch = 50,
			Fire = 51,
			MonsterSpawner = 52,
			StairsWooden = 53,
			Chest = 54,
			RedStoneWire = 55,
			DiamondOre = 56,
			DiamondBlock = 57,
			CraftingTable = 58,
			Seeds = 59,
			FarmLand = 60,
			Furnace = 61,
			FurnaceOn = 62,
			SignPost = 63,
			DoorWooden = 64,
			Ladder = 65,
			Rails = 66,
			StairsCobblestone = 67,
			SignWall = 68,
			Lever = 69,
			PressurePlateStone = 70,
			DoorIron = 71,
			PressurePlateWood = 72,
			RedStoneOre = 73,
			RedStoneOreGlow = 74,
			RedstoneTorchOff = 75,
			RedstoneTorchOn = 76,
			ButtonStone = 77,
			Snow = 78,
			Ice = 79,
			SnowBlock = 80,
			Cactus = 81,
			ClayBlock = 82,
			SugarCane = 83,
			Jukebox = 84,
			Fence = 85,
			Pumpkin = 86,
			Netherrack = 87,
			SouldSand = 88,
			GlowstoneBlock = 89,
			Portal = 90,
			JackOLantern = 91,
			CakeBlock = 92,
			RedstoneRepeaterOff = 93,
			RedstoneRepeaterOn = 94,
			//LockedChest = 95,
			Trapdoor = 96
		};
	}
}
